<a href="https://colab.research.google.com/github/HemaGarima/Mathematics-for-ML-DS/blob/master/Linear_Algebra_W1_Numpy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPy - Numerical Python

In [1]:
test = "Hello World"

In [2]:
print(test)

Hello World


In [3]:
import numpy as np

- in NumPy , all of the elements within the array are of the same type.

In [4]:
one_dimensional_arr = np.array([10,12])
print(one_dimensional_arr)

[10 12]


In [5]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [7]:
b = np.arange(3)
print(b)

[0 1 2]


In [8]:
c = np.arange(1,20,3)
print(c)

[ 1  4  7 10 13 16 19]


In [9]:
lin_spaced_arr = np.linspace(0,100,5)
print(lin_spaced_arr)

[  0.  25.  50.  75. 100.]


In [10]:
lin_spaced_arr_int = np.linspace(0,100,5,dtype = int)
print(lin_spaced_arr_int)

[  0  25  50  75 100]


In [11]:
c_int = np.arange(1,20,3,dtype = int)
print(c_int)

[ 1  4  7 10 13 16 19]


In [12]:
b_float = np.arange(3,dtype = float)
print(b_float)

[0. 1. 2.]


In [13]:
char_arr = np.array(['Welcome to Math for ML!'])
print(char_arr)
print(char_arr.dtype)

['Welcome to Math for ML!']
<U23


In [14]:
ones_arr = np.ones(3)
print(ones_arr)

[1. 1. 1.]


In [15]:
zeros_arr = np.zeros(3)
print(zeros_arr)

[0. 0. 0.]


In [16]:
empt_arr = np.empty(3)
print(empt_arr)

[0. 0. 0.]


In [18]:
rand_arr = np.random.rand(3)
print(rand_arr)

[0.50644208 0.29163215 0.17266496]


In [19]:
two_dim_arr = np.array([[1,2,3],[4,5,6]])
print(two_dim_arr)

[[1 2 3]
 [4 5 6]]


In [20]:
one_dim_arr = np.array([1,2,3,4,5,6])
multi_dim_arr = np.reshape(one_dim_arr , (2,3))
print(multi_dim_arr)

[[1 2 3]
 [4 5 6]]


In [21]:
multi_dim_arr.ndim

2

In [22]:
multi_dim_arr.shape

(2, 3)

In [23]:
multi_dim_arr.size

6

In [24]:
arr_1 = np.array([2,4,6])
arr_2 = np.array([1,3,5])

In [25]:
addition = arr_1 + arr_2
print(addition)

[ 3  7 11]


In [26]:
subtraction = arr_1 - arr_2
print(subtraction)

[1 1 1]


In [27]:
multiplication = arr_1 * arr_2
print(multiplication)

[ 2 12 30]


## Multiplying vector with a scalar ( broadcasting )

In [28]:
vector = np.array([1,2])
vector * 1.6

array([1.6, 3.2])

In [29]:
print(vector)

[1 2]


In [31]:
vector_ = vector*1.6
print(vector_)

[1.6 3.2]


In [32]:
a = ([1,2,3,4,5])
print(a[2])

3


In [33]:
print(a[0])

1


In [34]:
two_dim = np.array(([1,2,3],[4,5,6],[7,8,9]))

In [35]:
print(two_dim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
print(two_dim[2][1])

8


In [38]:
sliced_arr = a[1:4]
print(sliced_arr)

[2, 3, 4]


In [40]:
sliced_arr = a[:3]
print(sliced_arr)

[1, 2, 3]


In [41]:
sliced_arr = a[2:]
print(sliced_arr)

[3, 4, 5]


In [42]:
sliced_arr = a[::2]
print(sliced_arr)

[1, 3, 5]


In [43]:
print(a == a[:] == a[::])

True


In [44]:
sliced_arr_1 = two_dim[0:2]
sliced_arr_1

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
sliced_two_dim_rows = two_dim[1:3]
print(sliced_two_dim_rows)

[[4 5 6]
 [7 8 9]]


In [46]:
sliced_two_dim_cols = two_dim[:,1]
print(sliced_two_dim_cols)

[2 5 8]


In [48]:
a1 = np.array([[1,1],[2,2]])
a2 = np.array([[3,3],[4,4]])
print(f'a1:\n{a1}')
print(f'a2:\n{a2}')

a1:
[[1 1]
 [2 2]]
a2:
[[3 3]
 [4 4]]


In [49]:
ver_stack = np.vstack((a1,a2))
print(ver_stack)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [50]:
horz_stack = np.hstack((a1,a2))
print(horz_stack)

[[1 1 3 3]
 [2 2 4 4]]


In [51]:
pip install quiz