<a href="https://colab.research.google.com/github/HemaGarima/Mathematics-for-ML-DS/blob/master/Linear_Algebra_W_2_Numpy_linalg_sub_librarys.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import numpy as np

In [22]:
A = np.array([[4,-3,1],[2,1,3],[-1,2,-5]],dtype = np.dtype(float))
b = np.array([-10,0,17],dtype = np.dtype(float))
print("Matrix A:")
print(A)
print("Matrix B:")
print(b)

Matrix A:
[[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]]
Matrix B:
[-10.   0.  17.]


In [23]:
print(f"Shape of A: {np.shape(A)}")
print(f"Shape of B: {np.shape(b)}")

Shape of A: (3, 3)
Shape of B: (3,)


In [24]:
x = np.linalg.solve(A,b)
print(f"Solution : {x}")

Solution : [ 1.  4. -2.]


In [25]:
d = np.linalg.det(A)
print(f"Determinant of matrix A : , {d:.2f}")

Determinant of matrix A : , -60.00


In [26]:
A_system = np.hstack((A , b.reshape((3,1))))
print(A_system)

[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]


In [27]:
def MultiplyRow(M , row_num , row_num_multiple):
  M_new = M.copy()
  M_new[row_num] = M_new[row_num] * row_num_multiple
  return M_new

In [28]:
print("Original Matrix : ")
print(A_system)
print("\nMatrix after its third row is multiplied by 2 : ")
print(MultiplyRow(A_system , 2 , 2))

Original Matrix : 
[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]

Matrix after its third row is multiplied by 2 : 
[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -2.   4. -10.  34.]]


In [29]:
def AddRows(M , row_num_1 , row_num_2 , row_num_1_multiple):
  M_new = M.copy()
  M_new[row_num_2] = row_num_1_multiple * M_new[row_num_1] + M_new[row_num_2]
  return M_new

In [30]:
print("Original Matrix : ")
print(A_system)
print("\nMatrix after exchange of the third row with the sum of itself and second row multiplied by 1/2:")
print(AddRows(A_system,1,2,1/2))

Original Matrix : 
[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]

Matrix after exchange of the third row with the sum of itself and second row multiplied by 1/2:
[[  4.   -3.    1.  -10. ]
 [  2.    1.    3.    0. ]
 [  0.    2.5  -3.5  17. ]]


In [31]:
def SwapRows(M , row_num_1 , row_num_2):
  M_new = M.copy()
  M_new[[row_num_1,row_num_2]] = M_new[[row_num_2,row_num_1]]
  return M_new

In [32]:
print("Original Matrix : ")
print(A_system)
print("\nMatrix after exchange its first and third rows")
print(SwapRows(A_system,0,2))

Original Matrix : 
[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]

Matrix after exchange its first and third rows
[[ -1.   2.  -5.  17.]
 [  2.   1.   3.   0.]
 [  4.  -3.   1. -10.]]


In [33]:
A_ref = SwapRows(A_system,0,2)
print(A_ref)

[[ -1.   2.  -5.  17.]
 [  2.   1.   3.   0.]
 [  4.  -3.   1. -10.]]


In [34]:
A_ref = AddRows(A_ref , 0 , 1 , 2)
print(A_ref)

[[ -1.   2.  -5.  17.]
 [  0.   5.  -7.  34.]
 [  4.  -3.   1. -10.]]


In [35]:
A_ref = AddRows(A_ref , 0 , 2 , 4)
print(A_ref)

[[ -1.   2.  -5.  17.]
 [  0.   5.  -7.  34.]
 [  0.   5. -19.  58.]]


In [36]:
A_ref = AddRows(A_ref , 1 , 2 , -1)
print(A_ref)

[[ -1.   2.  -5.  17.]
 [  0.   5.  -7.  34.]
 [  0.   0. -12.  24.]]


In [37]:
A_ref = MultiplyRow(A_ref , 2 , -1/12)
print(A_ref)

[[-1.  2. -5. 17.]
 [ 0.  5. -7. 34.]
 [-0. -0.  1. -2.]]


In [38]:
x_3 = -2
x_2 = (A_ref[1,3]-A_ref[1,2]*x_3) / A_ref[1,1]
x_1 = (A_ref[0,3]-A_ref[0,2]*x_3-A_ref[0,1]*x_2)/A_ref[0,0]
print(x_1 , x_2 , x_3)

1.0 4.0 -2


In [39]:
A_2 = np.array([
    [1,1,1],
    [0,1,-3],
    [2,1,5]
],dtype = np.dtype(float))
b_2 = np.array([2,1,0],dtype = np.dtype(float))
d_2 = np.linalg.det(A_2)
print(f"Determinant of matrix A_2 : {d_2 : .2f}")

Determinant of matrix A_2 :  0.00


In [42]:
# x_2 = np.linalg.solve(A_2 , b_2)

LinAlgError: Singular matrix

In [43]:
A_2_system = np.hstack((A_2 , b_2.reshape((3,1))))
print(A_2_system)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 2.  1.  5.  0.]]


In [44]:
A_2_ref = AddRows(A_2_system , 0 , 2 , -2)
print(A_2_ref)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 0. -1.  3. -4.]]


In [45]:
A_2_ref = AddRows(A_2_ref , 1 ,2 ,1)
print(A_2_ref)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 0.  0.  0. -3.]]


In [46]:
b_3 = np.array([2,1,3])

In [47]:
A_3_system = np.hstack((A_2 , b_3.reshape((3,1))))
print(A_3_system)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 2.  1.  5.  3.]]


In [48]:
A_3_ref = AddRows(A_3_system , 0 , 2 , -2)
print(A_3_ref)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 0. -1.  3. -1.]]


In [49]:
A_3_ref = AddRows(A_3_ref , 1 , 2 ,1)
print(A_3_ref)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 0.  0.  0.  0.]]
