<a href="https://colab.research.google.com/github/HemaGarima/Mathematics-for-ML-DS/blob/master/Linear_algebra_w1_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
A = np.array([[-1,3],[3,2]] , dtype = np.dtype(float))
b = np.array([7,1] , dtype = np.dtype(float))
print("Matrix A:")
print(A)
print("Matrix b:")
print(b)

Matrix A:
[[-1.  3.]
 [ 3.  2.]]
Matrix b:
[7. 1.]


In [4]:
print(f"Shape of A: {A.shape}")
print(f"Shape of b: {b.shape}")

Shape of A: (2, 2)
Shape of b: (2,)


In [5]:
x = np.linalg.solve(A,b)
print(f"Solution: {x}")

Solution: [-1.  2.]


In [6]:
-1*-1 + 3*2

7

In [7]:
3*-1 + 2*2

1

- Linear System containing two(or more) equations with the same number of unknown variables will have one solution if and only if matrix A has non-zero determinant.

In [8]:
d = np.linalg.det(A)
print(f"Determinant of matrix A: {d:.2f}")

Determinant of matrix A: -11.00


In [9]:
A_system = np.hstack((A,b.reshape((2,1))))
print(A_system)

[[-1.  3.  7.]
 [ 3.  2.  1.]]


In [10]:
print(A_system[1])

[3. 2. 1.]
