<a href="https://colab.research.google.com/github/HemaGarima/Mathematics-for-ML-DS/blob/master/Linear_Algebra_W2_numpy_linalg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
import numpy as np

# 1 - Representing and solving a system of linear equations using matrices

### 1.1 - Solving system of linear equations using matrices

In [44]:
A = np.array([
    [4,-3,1],
    [2,1,3],
    [-1,2,-5]
] , dtype = np.dtype(float))
b = np.array([10,0,-7],dtype = np.dtype(float))
print("Matrix A:")
print(A)
print("\nArray b:")
print(b)

Matrix A:
[[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]]

Array b:
[10.  0. -7.]


In [45]:
A.shape , b.shape

((3, 3), (3,))

In [46]:
print(f"Shape of A: {np.shape(A)}")
print(f"Shape of B: {np.shape(b)}")

Shape of A: (3, 3)
Shape of B: (3,)


In [47]:
x = np.linalg.solve(A,b)

In [48]:
print(f"Solution : {x}")

Solution : [ 0.66666667 -2.33333333  0.33333333]


In [49]:
4 * 0.6666667 + (-3)*(-2.33333333) + 1*0.3333333

10.000000089999999

### 1.2 - Evaluating the determinant of a matrix

In [50]:
d = np.linalg.det(A)

In [51]:
print(f"Determinant of matrix A: {d:.2f}")

Determinant of matrix A: -60.00


- Determinant value is non-zero thus matrix is non-singular.

# 2 - Solving system of linear equations using row reduction

### 2.1 - Preparation for row reduction

In [52]:
 b = b.reshape((3,1))

In [53]:
b.shape

(3, 1)

In [54]:
A_system = np.hstack((A,b))

In [55]:
A_system

array([[ 4., -3.,  1., 10.],
       [ 2.,  1.,  3.,  0.],
       [-1.,  2., -5., -7.]])

In [56]:
print(A_system)

[[ 4. -3.  1. 10.]
 [ 2.  1.  3.  0.]
 [-1.  2. -5. -7.]]


### 2.2 - Functions for elementary operations

In [57]:
def MultiplyRow(M , row_num , row_num_multiple):
  M_new = M.copy()
  M_new[row_num] = M_new[row_num] * row_num_multiple
  return M_new

In [58]:
print("Original matrix : ")
print(A_system)

Original matrix : 
[[ 4. -3.  1. 10.]
 [ 2.  1.  3.  0.]
 [-1.  2. -5. -7.]]


In [59]:
print("\nMatrix after its third row is multiplied by 2:")
print(MultiplyRow(A_system,2,2))


Matrix after its third row is multiplied by 2:
[[  4.  -3.   1.  10.]
 [  2.   1.   3.   0.]
 [ -2.   4. -10. -14.]]


In [60]:
def AddRows(M , row_num_1 , row_num_2 , row_num_1_multiple):
  M_new = M.copy()
  M_new[row_num_2] = row_num_1_multiple * M_new[row_num_1] + M_new[row_num_2]
  return M_new

In [61]:
print("Original Matrix : ")
print(A_system)

Original Matrix : 
[[ 4. -3.  1. 10.]
 [ 2.  1.  3.  0.]
 [-1.  2. -5. -7.]]


In [62]:
print("\nMatrix after exchange of the third row with the sum of itself and second row multiplied by 1/2:")


Matrix after exchange of the third row with the sum of itself and second row multiplied by 1/2:


In [63]:
print(AddRows(A_system , 1, 2, 1/2))

[[ 4.  -3.   1.  10. ]
 [ 2.   1.   3.   0. ]
 [ 0.   2.5 -3.5 -7. ]]


In [64]:
def SwapRows(M , row_num_1 , row_num_2):
  M_new = M.copy()
  M_new[[row_num_1 , row_num_2]] = M_new[[row_num_2 , row_num_1]]
  return M_new

In [65]:
print("Original Matrix:")
print(A_system)

Original Matrix:
[[ 4. -3.  1. 10.]
 [ 2.  1.  3.  0.]
 [-1.  2. -5. -7.]]


In [66]:
print(("\n Matrix after exchange its first and third rows : "))
print(SwapRows(A_system,0,2))


 Matrix after exchange its first and third rows : 
[[-1.  2. -5. -7.]
 [ 2.  1.  3.  0.]
 [ 4. -3.  1. 10.]]


### 2.3 - Row Reduction and Solution of the linear system

In [67]:
A_ref = SwapRows(A_system,0,2)
print(A_ref)

[[-1.  2. -5. -7.]
 [ 2.  1.  3.  0.]
 [ 4. -3.  1. 10.]]


In [68]:
A_ref = AddRows(A_ref , 0 , 1 , 2)
print(A_ref)

[[ -1.   2.  -5.  -7.]
 [  0.   5.  -7. -14.]
 [  4.  -3.   1.  10.]]


In [69]:
A_ref = AddRows(A_ref , 0 , 2 , 4)
print(A_ref)

[[ -1.   2.  -5.  -7.]
 [  0.   5.  -7. -14.]
 [  0.   5. -19. -18.]]


In [70]:
A_ref = AddRows(A_ref , 1 , 2 , -1)
print(A_ref)

[[ -1.   2.  -5.  -7.]
 [  0.   5.  -7. -14.]
 [  0.   0. -12.  -4.]]


In [71]:
A_ref = MultiplyRow(A_ref , 2 , -1/12)
print(A_ref)

[[ -1.           2.          -5.          -7.        ]
 [  0.           5.          -7.         -14.        ]
 [ -0.          -0.           1.           0.33333333]]


In [72]:
x_3 = -2
x_2 = (A_ref[1,3] - A_ref[1,2] * x_3) / A_ref[1,1]
x_1 = (A_ref[0,3] - A_ref[0,2] * x_3 - A_ref[0,1] * x_2)/A_ref[0,0]

In [73]:
print(x_1 , x_2 , x_3)

5.800000000000001 -5.6 -2


# 3 - System of Linear Equations with No solutions

In [74]:
A_2 = np.array([
    [1,1,1],
    [0,1,-3],
    [2,1,5]
],dtype = np.dtype(float))

In [75]:
b_2 = np.array([2,1,0] , dtype = np.dtype(float))

In [76]:
d_2 = np.linalg.det(A_2)

In [77]:
print(f"Determinant of matrix A_2: {d_2 : .2f}")

Determinant of matrix A_2:  0.00


- determinant is zero thus matrix is singular and it has infinitely many solution or no solution

In [78]:
# x_2 = np.linalg.solve(A_2 , b_2) --> gives and error because matrix is singular it has no solution or infinitely many solutions

In [79]:
A_2_system = np.hstack((A_2 , b_2.reshape((3,1))))

In [80]:
print(A_2_system)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 2.  1.  5.  0.]]


In [81]:
A_2_ref = AddRows(A_2_system,0,2,-2)

In [82]:
print(A_2_ref)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 0. -1.  3. -4.]]


In [83]:
A_2_ref = AddRows(A_2_ref , 1 , 2 , 1)
print(A_2_ref)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 0.  0.  0. -3.]]


- The last row will correspond to the equation 0 = -3 which has no solution.

# 4 - System of Linear Equations with infinite number of solutions

- You can bring system (2) to consistency by changing only the free coefficients.

In [84]:
b_3 = np.array([2,1,3])

In [85]:
A_3_system = np.hstack((A_2 , b_3.reshape((3,1))))
print(A_3_system)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 2.  1.  5.  3.]]


In [86]:
A_3_ref = AddRows(A_3_system , 0 , 2 , -2)
print(A_3_ref)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 0. -1.  3. -1.]]


In [87]:
A_3_ref = AddRows(A_3_ref , 1 , 2 , 1)
print(A_3_ref)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 0.  0.  0.  0.]]
