<a href="https://colab.research.google.com/github/HemaGarima/Mathematics-for-ML-DS/blob/master/Linear_Algebra_W1_NumpyArrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
test = "Hello World"

In [2]:
print(test)

Hello World


In [3]:
import numpy as np

In [4]:
one_dimensional_arr = np.array([10,12])
print(one_dimensional_arr)

[10 12]


In [5]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
b = np.arange(3)
print(b)

[0 1 2]


In [7]:
c = np.arange(1,20,3)

In [8]:
print(c)

[ 1  4  7 10 13 16 19]


In [9]:
lin_spaced_arr = np.linspace(0,100,5)
print(lin_spaced_arr)

[  0.  25.  50.  75. 100.]


In [10]:
lin_spaced_arr_int = np.linspace(0,100,5,dtype = int)

In [12]:
print(lin_spaced_arr_int)

[  0  25  50  75 100]


In [13]:
c_int = np.arange(1,20,3,dtype = int)
print(c_int)

[ 1  4  7 10 13 16 19]


In [14]:
b_float = np.arange(3,dtype = float)
print(b_float)

[0. 1. 2.]


In [15]:
char_arr = np.array(['Welcome to Math for ML! '])
print(char_arr)
print(char_arr.dtype)

['Welcome to Math for ML! ']
<U24


In [16]:
ones_arr = np.ones(3)
print(ones_arr)

[1. 1. 1.]


In [17]:
zeros_arr = np.zeros(3)
print(zeros_arr)

[0. 0. 0.]


In [18]:
empt_arr = np.empty(3)
print(empt_arr)

[0. 0. 0.]


In [19]:
rand_arr = np.random.rand(3)
print(rand_arr)

[0.98471303 0.70015421 0.05344955]


In [20]:
two_dim_arr = np.array([[1,2,3],[4,5,6]])
print(two_dim_arr)

[[1 2 3]
 [4 5 6]]


In [21]:
one_dim_arr = np.array([1,2,3,4,5,6])
multi_dim_arr = np.reshape(one_dim_arr,(2,3))
print(multi_dim_arr)

[[1 2 3]
 [4 5 6]]


In [22]:
multi_dim_arr.ndim

2

In [23]:
multi_dim_arr.shape

(2, 3)

In [24]:
multi_dim_arr.size

6

In [25]:
arr_1 = np.array([2,4,6])
arr_2 = np.array([1,3,5])
addition = arr_1 + arr_2
print(addition)
subtraction = arr_1 - arr_2
print(subtraction)
multiplication = arr_1*arr_2
print(multiplication)

[ 3  7 11]
[1 1 1]
[ 2 12 30]


In [26]:
vector = np.array([1,2])
vector*1.6

array([1.6, 3.2])

In [27]:
a = ([1,2,3,4,5])
print(a[2])

3


In [28]:
print(a[0])

1


In [29]:
two_dim = np.array(([1,2,3],[4,5,6],[7,8,9]))
print(two_dim[2][1])

8


In [30]:
sliced_arr = a[1:4]
print(sliced_arr)

[2, 3, 4]


In [31]:
sliced_arr = a[:3]
print(sliced_arr)

[1, 2, 3]


In [32]:
sliced_arr = a[2:]
print(sliced_arr)

[3, 4, 5]


In [33]:
sliced_arr = a[::2]
print(sliced_arr)

[1, 3, 5]


In [34]:
print(a == a[:] == a[::])

True


In [35]:
sliced_arr_1 = two_dim[0:2]
sliced_arr_1

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
sliced_two_dim_rows = two_dim[1:3]
print(sliced_two_dim_rows)

[[4 5 6]
 [7 8 9]]


In [37]:
sliced_two_dim_cols = two_dim[:,1]
print(sliced_two_dim_cols)

[2 5 8]


In [38]:
a1 = np.array([[1,1],[2,2]])
a2 = np.array([[3,3],[4,4]])
print(f'a1:\n{a1}')
print(f'a2:\n{a2}')

a1:
[[1 1]
 [2 2]]
a2:
[[3 3]
 [4 4]]


In [39]:
vert_stack = np.vstack((a1,a2))
print(vert_stack)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [40]:
horz_stack = np.hstack((a1,a2))
print(horz_stack)

[[1 1 3 3]
 [2 2 4 4]]
